### ISSUE TITLE
As a user, I want to produce a report for the number of people who speak Chinese, English, Hindi, Spanish, and Arabic from greatest number to smallest including the percentage of the world population so that I can gain insights of global language distributions.

### ISSUE THREAD

**Issue by seinlei** [Edinburgh-Software-Engineering-Methods/sem#32]

**Comment by MunaSamaha** [comment]
As a user, I want to produce a report for the number of people who speak Chinese, English, Hindi, Spanish, and Arabic from greatest number to smallest including the percentage of the world population so that I can gain insights of global language distributions. #32
